services:
  web:
    build:
      context: angular
      target: dev-envs
    ports:
      - 5200:5200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./angular:/project
      - /project/node_modules
